# Cloud Build configuration for automatic deployment
steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    
  # Build the application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

# Build timeout
timeout: '1200s'

# Substitutions for environment variables (optional)
substitutions:
  _NODE_ENV: 'production'

# Cloud Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'